[tool.poetry]
name = "livetalking-fork"
version = "0.1.0"
description = ""
authors = ["xfylsj <xfylsj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
